services:
  database:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=quiz_db
    ports:
      - "0:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 1s
      retries: 3
    volumes:
      - pg_data:/var/lib/postgresql/data

  api:
    build: api
    container_name: api
    depends_on:
      database:
        condition: service_healthy
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=quiz_db
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8000"]
      interval: 10s
      timeout: 1s
      retries: 3
    stdin_open: true
    tty: true

  test:
    build: test
    container_name: test
    depends_on:
      api:
        condition: service_healthy

volumes:
  pg_data:
